# Generated by Django 4.2.6 on 2023-10-21 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birdie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birdieupdate',
            options={'ordering': ['-created_at']},
        ),
    ]
