# Generated by Django 4.2.6 on 2023-10-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdie', '0002_alter_birdieupdate_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
